// ===== DATA =====
const messagesData={inbox:[{id:1,sender:'John Smith',email:'john.smith@email.com',phone:'(305) 555-1234',subject:'Question about 1505 N Jean Baptiste Pointe du Sable Lake Shore Dr',time:'2 hours ago',status:'new',unread:true,thread:[{type:'incoming',text:"Hi, I'm very interested in your property at 1505 N Jean Baptiste Pointe du Sable Lake Shore Dr. Is the price negotiable?",sender:'John Smith',time:'2 hours ago',documents:[]}]},{id:2,sender:'Sarah Johnson',email:'sarah.johnson@email.com',phone:'(305) 555-5678',subject:'Visit confirmation for 456 Ocean Drive',time:'Yesterday',status:'read',unread:false,thread:[{type:'incoming',text:"Hi! I'd like to schedule a visit.",sender:'Sarah Johnson',time:'3 days ago',documents:[]},{type:'outgoing',text:"Hi Sarah! Yes, Thursday at 2:30 PM works perfectly.",sender:'You',time:'2 days ago',documents:[]},{type:'incoming',text:"Thank you for accepting my visit request!",sender:'Sarah Johnson',time:'Yesterday',documents:[]}]},{id:3,sender:'Michael Chen',email:'michael.chen@email.com',phone:'(305) 555-9012',subject:'Offer inquiry',time:'2 days ago',status:'new',unread:true,thread:[{type:'incoming',text:"Hello, I saw your listing and I'm interested in making an offer.",sender:'Michael Chen',time:'2 days ago',documents:[]}]},{id:4,sender:'Emily Davis',email:'emily.davis@email.com',phone:'(305) 555-3456',subject:'Property documents received',time:'3 days ago',status:'replied',unread:false,thread:[{type:'incoming',text:"Could you send me the property disclosure documents?",sender:'Emily Davis',time:'4 days ago',documents:[]},{type:'outgoing',text:"Of course! I've attached the documents.",sender:'You',time:'3 days ago',documents:[{name:'Property_Disclosure.pdf',size:'245 KB',type:'pdf'}]},{type:'incoming',text:"Thanks for sending the documents.",sender:'Emily Davis',time:'3 days ago',documents:[]}]}],sent:[]};

let selectedMessageId=null,currentVisitCard=null,currentBuyerName='',currentPropertyAddress='',pendingVisitsCount=2,pendingOffersCount=1,isComposingMessage=false,composingMessageTo='',isReplyingToMessage=false,replyingToMessageId=null,currentCancelOwnerName='',currentCancelPropertyAddress='',currentCancelCardId='',visitedPages={};

let notificationsData=[{id:1,type:'offer',icon:'💰',title:'<strong>John Smith</strong> submitted an offer on <strong>123 Main Street</strong>',time:'2 hours ago',unread:true,link:'offers'},{id:2,type:'visit',icon:'📅',title:'<strong>Sarah Johnson</strong> requested a visit',time:'5 hours ago',unread:true,link:'visits'},{id:3,type:'message',icon:'💬',title:'<strong>Michael Chen</strong> sent you a message',time:'2 days ago',unread:true,link:'messages'},{id:4,type:'visit',icon:'✅',title:'Visit confirmed for <strong>789 Palm Avenue</strong>',time:'3 days ago',unread:true,link:'visits'}];

let currentCalendarDate=new Date(2026,1,1),currentCalendarView='month',selectedEventData=null,selectedProperties=['all'],selectedPropertiesOffers=['all'],selectedPropertiesVisits=['all'],selectedPropertiesMessages=['all'],selectedPropertiesProperties=['all'],mobilePendingFiles=[],chatPendingFiles=[],currentMobileMessageId=null,currentMessageFilter='all';

let calendarEvents=[{id:1,type:'visit',status:'confirmed',title:'789 Palm Avenue, Coral Gables, FL',shortTitle:'789 Palm Avenue',date:new Date(2026,1,2,11,0),person:'David Miller',phone:'(305) 555-9012',email:'david.miller@email.com',property:'789 Palm Avenue'},{id:2,type:'visit',status:'pending',title:'1505 N Jean Baptiste Pointe du Sable Lake Shore Dr, Bonadelle Ranchos-Madera Ranchos, CA 33135',shortTitle:'1505 N Jean Baptiste...',date:new Date(2026,0,28,10,0),person:'John Smith',phone:'(305) 555-1234',email:'john.smith@email.com',property:'1505 N Jean Baptiste Pointe du Sable Lake Shore Dr'}];

let properties=[{id:'all',name:'All Properties'},{id:'1505 N Jean Baptiste Pointe du Sable Lake Shore Dr',name:'1505 N Jean Baptiste Pointe du Sable Lake Shore Dr, Bonadelle Ranchos-Madera Ranchos, CA 33135'},{id:'456 Ocean Drive',name:'456 Ocean Drive, Miami Beach, FL'},{id:'789 Palm Avenue',name:'789 Palm Avenue, Coral Gables, FL'}];

// ===== INIT =====
function setGreeting(){const h=new Date().getHours();let g=h<12?'Good morning':h<17?'Good afternoon':'Good evening';let i=h<12?'☀️':h<17?'🌤️':'🌙';document.getElementById('navGreeting').innerHTML='<span style="font-size: 20px; line-height: 1;">'+i+'</span> '+g+', John Doe';}

// ===== DROPDOWNS & MENUS =====
function closeAllDropdowns(){document.querySelectorAll('.menu, .dashboard-menu, .notifications-menu').forEach(m=>m.classList.remove('show'));document.body.style.overflow='';}
function toggleMenu(menuId,e){e.stopPropagation();e.preventDefault();const m=document.getElementById(menuId);const isOpen=m.classList.contains('show');closeAllDropdowns();if(!isOpen){m.classList.add('show');if(window.innerWidth<=1024)document.body.style.overflow='hidden';if(menuId==='notificationsMenu')renderNotifications();if(menuId==='propertyFilterMenu')renderPropertyFilter();}}

// ===== NOTIFICATIONS =====
function renderNotifications(){document.getElementById('notificationsList').innerHTML=notificationsData.map(n=>'<div class="notification-item '+(n.unread?'unread':'')+'" onclick="handleNotificationClick('+n.id+",\'"+n.link+'\',event)"><div class="notification-icon '+n.type+'">'+n.icon+'</div><div class="notification-content"><div class="notification-title">'+n.title+'</div><div class="notification-meta">'+(n.unread?'<span class="notification-dot"></span>':'')+'<span>'+n.time+'</span></div></div></div>').join('');}
function handleNotificationClick(id,link,e){e.stopPropagation();const n=notificationsData.find(x=>x.id===id);if(n)n.unread=false;updateNotificationsBadge();document.getElementById('notificationsMenu').classList.remove('show');showPage(link,e);}
function markAllNotificationsRead(e){e.stopPropagation();notificationsData.forEach(n=>n.unread=false);updateNotificationsBadge();renderNotifications();}
function updateNotificationsBadge(){const c=notificationsData.filter(n=>n.unread).length;const b=document.getElementById('notificationsBadge');const btn=document.querySelector('.notifications-btn');if(c>0){b.textContent=c;b.style.display='flex';btn.classList.add('has-unread');}else{b.style.display='none';btn.classList.remove('has-unread');}}

// ===== UTILITIES =====
function isDesktopView(){return window.innerWidth>1024;}
function closeModal(id){document.getElementById(id).classList.remove('show');}
function showMobileToast(msg){const t=document.createElement('div');t.style.cssText='position: fixed; bottom: 100px; left: 50%; transform: translateX(-50%); background: var(--c-primary); color: white; padding: 12px 24px; border-radius: 24px; font-size: 14px; font-weight: 500; z-index: 9999;';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>{t.style.opacity='0';t.style.transition='opacity 0.3s';setTimeout(()=>t.remove(),300);},2000);}
function formatFileSize(b){if(b===0)return'0 Bytes';const k=1024;const s=['Bytes','KB','MB','GB'];const i=Math.floor(Math.log(b)/Math.log(k));return parseFloat((b/Math.pow(k,i)).toFixed(1))+' '+s[i];}

// ===== NAVIGATION =====
function mobileNavTo(page,e){e.preventDefault();document.querySelectorAll('.mobile-bottom-nav-item').forEach(i=>i.classList.remove('active'));e.currentTarget.classList.add('active');showPage(page,e);}
function updateMobileBadges(){const vb=document.getElementById('mobileVisitsBadge');if(vb){if(pendingVisitsCount>0){vb.textContent=pendingVisitsCount;vb.style.display='flex';}else vb.style.display='none';}const unread=messagesData.inbox.filter(m=>m.unread).length;const mb=document.getElementById('mobileMessagesBadge');if(mb){if(unread>0){mb.textContent=unread;mb.style.display='flex';}else mb.style.display='none';}}
function showPage(page,e){if(e)e.preventDefault();['offersPage','propertiesPage','visitsPage','messagesPage','calendarPage','accountPage','contractsPage','addPropertyPage'].forEach(p=>document.getElementById(p).style.display='none');document.querySelectorAll('.nav-link').forEach(l=>l.classList.remove('active'));document.getElementById(page+'Page').style.display='block';if(e&&e.target)e.target.classList.add('active');document.querySelectorAll('.mobile-bottom-nav-item').forEach(i=>{i.classList.remove('active');if(i.getAttribute('onclick')&&i.getAttribute('onclick').includes("'"+page+"'"))i.classList.add('active');});if(page==='calendar'){currentCalendarDate=new Date(2026,1,1);renderCalendar();}showPageContextMessage(page);}
function showPageContextMessage(page,subTab){if(!isDesktopView())return;const pk=page+(subTab?'-'+subTab:'');if(visitedPages[pk])return;visitedPages[pk]=true;let msg='';if(page==='visits'){if(pendingVisitsCount>0)msg='👋 You have <strong>'+pendingVisitsCount+' visit request'+(pendingVisitsCount>1?'s':'')+' waiting</strong>! Would you like me to help you respond to them?<div style="margin-top: 12px;"><button class="btn btn-p" onclick="this.parentElement.parentElement.style.display=\'none\'; document.getElementById(\'visit1\')?.scrollIntoView({behavior:\'smooth\'})">Let\'s do it</button></div>';else msg='✨ All caught up on visits!';}else if(page==='offers'){if(pendingOffersCount>0)msg='💰 You have <strong>'+pendingOffersCount+' pending offer</strong> that expires soon! Want me to explain your options?<div style="margin-top: 12px;"><button class="btn btn-p" onclick="this.parentElement.parentElement.style.display=\'none\'">Show me my options</button></div>';else msg='✨ No pending offers right now.';}else if(page==='properties')msg='🏠 Here are your listings. Need help adding a new property or updating an existing one? Just ask!';else if(page==='messages'){const unread=messagesData.inbox.filter(m=>m.unread).length;if(unread>0)msg='💬 You have <strong>'+unread+' unread message'+(unread>1?'s':'')+'</strong>! I can help you draft quick responses. Just click on a message.';else msg='✨ All messages read!';}else if(page==='calendar')msg='📅 Your calendar shows all visits, deadlines, and milestones. Want me to add an important date?';else if(page==='contracts')msg='📋 Here you\'ll find all the legal forms you need for your state. Not sure which one? Just ask me!';else if(page==='account')msg='⚙️ Manage your profile and preferences here. Need help with anything?';if(msg)setTimeout(()=>addChatMessage(msg),500);}

// ===== CHAT =====
function addChatMessage(msg,isUser=false){const cm=document.getElementById('chatMessages');const d=document.createElement('div');d.className='chat-message '+(isUser?'user':'bot');d.innerHTML='<div><div class="message-bubble">'+msg+'</div></div>';cm.appendChild(d);cm.scrollTop=cm.scrollHeight;}
function sendChatMessage(){const i=document.getElementById('chatInput');const msg=i.value.trim();if(!msg&&chatPendingFiles.length===0)return;addChatMessage(msg||'📎 Sent '+chatPendingFiles.length+' attachment(s)',true);i.value='';if(isComposingMessage)handleComposedMessage(msg);else if(isReplyingToMessage&&replyingToMessageId)handleReplyToMessage(msg);else{chatPendingFiles=[];setTimeout(()=>addChatMessage("I can help with that! What would you like to do?"),800);}}
function handleReplyToMessage(text){const m=messagesData.inbox.find(x=>x.id===replyingToMessageId);if(!m)return;m.thread.push({type:'outgoing',text:text||'Sent attachment(s)',sender:'You',time:'Just now',documents:[...chatPendingFiles]});m.status='replied';chatPendingFiles=[];setTimeout(()=>{addChatMessage('✅ Your reply has been sent to <strong>'+m.sender+'</strong>!');document.getElementById('chatInput').placeholder='Ask Artur anything…';isReplyingToMessage=false;replyingToMessageId=null;},600);renderInboxMessages();}
function handleChatKeypress(e){if(e.key==='Enter')sendChatMessage();}
function openMobileChat(){document.querySelector('.chat-widget').classList.add('mobile-open');}
function closeMobileChat(){document.querySelector('.chat-widget').classList.remove('mobile-open');}
function handleMobileNavChatKeypress(e){if(e.key==='Enter')sendMobileNavChat();}
function sendMobileNavChat(){const input=document.getElementById('mobileNavChatInput');const text=input.value.trim();if(!text)return;input.value='';showMobileToast('Message sent to Artur!');}
function triggerChatFileUpload(){document.getElementById('chatFileInput').click();}
function handleChatFileSelect(e){const f=e.target.files;for(let i=0;i<f.length;i++)chatPendingFiles.push({name:f[i].name,size:formatFileSize(f[i].size),type:f[i].name.split('.').pop().toLowerCase()});renderChatPendingAttachments();e.target.value='';}
function renderChatPendingAttachments(){const c=document.getElementById('chatPendingAttachments');if(chatPendingFiles.length===0){c.style.display='none';return;}c.style.display='flex';c.innerHTML=chatPendingFiles.map((f,i)=>'<div class="pending-attachment">'+f.name+'<button onclick="removeChatPendingFile('+i+')">×</button></div>').join('');}
function removeChatPendingFile(i){chatPendingFiles.splice(i,1);renderChatPendingAttachments();}
function askArturAbout(topic){if(!isDesktopView()){openMobileChat();}let msg='';if(topic==='notifications')msg='📱 <strong>About Notifications:</strong><br><br>• <strong>Email</strong> - Get updates about offers, visits, and messages<br>• <strong>SMS</strong> - Quick alerts for time-sensitive items<br>• <strong>Phone</strong> - Only for urgent matters (rarely used)<br>• <strong>Marketing</strong> - Tips and market updates (optional)<br><br>I recommend keeping Email and SMS on so you never miss an offer!';else if(topic==='contracts')msg='📋 <strong>About Contracts:</strong><br><br>These are official state-approved forms. Pick your state first, then choose the category:<br>• <strong>Sell</strong> - Purchase agreements<br>• <strong>Rent</strong> - Lease forms<br>• <strong>Disclosure</strong> - Required property disclosures<br>• <strong>Agreement</strong> - Listing and commission forms<br><br>Need help filling one out? Just ask!';addChatMessage(msg);}

// ===== MESSAGES =====
function showMessageModal(name,address,email,phone,title){if(isDesktopView()){addChatMessage('Contact '+name,true);setTimeout(()=>{let ci='📋 <strong>'+name+'</strong><br>';if(phone)ci+='📞 '+phone+'<br>';if(email)ci+='✉️ '+email;const cm=document.getElementById('chatMessages');const d=document.createElement('div');d.className='chat-message bot';d.innerHTML='<div><div class="message-bubble">'+ci+'<br><br>Would you like to send a message?</div><div style="display: flex; gap: 8px; margin-top: 12px;"><button class="btn" onclick="closeMessageChat(this)">Cancel</button><button class="btn btn-success" onclick="openMessageFromChat(this,\''+name+'\',\''+address+'\',\''+email+'\',\''+phone+'\',\''+title+'\')">Send a Message</button></div></div>';cm.appendChild(d);cm.scrollTop=cm.scrollHeight;},600);}else{document.getElementById('messageModalTitle').textContent=title||'Message to';document.getElementById('messageModalAddress').textContent=address;document.getElementById('messageModalName').textContent=name;document.getElementById('messageModalPhone').textContent=phone||'';document.getElementById('messageModalPhoneRow').href=phone?'tel:'+phone:'#';document.getElementById('messageModalPhoneRow').style.display=phone?'flex':'none';document.getElementById('messageModalEmail').textContent=email||'';document.getElementById('messageModalEmailRow').href=email?'mailto:'+email:'#';document.getElementById('messageModalEmailRow').style.display=email?'flex':'none';document.getElementById('messageModalDivider').style.display=(phone&&email)?'inline':'none';document.getElementById('messageText').value='';document.getElementById('messageModal').classList.add('show');}}
function closeMessageChat(btn){btn.parentElement.style.display='none';addChatMessage('Cancel',true);isComposingMessage=false;composingMessageTo='';document.getElementById('chatInput').placeholder='Ask Artur anything…';setTimeout(()=>addChatMessage('No problem!'),600);}
function openMessageFromChat(btn,name,address,email,phone,title){btn.parentElement.style.display='none';addChatMessage('Send a Message',true);isComposingMessage=true;composingMessageTo=name;setTimeout(()=>{addChatMessage('✍️ What would you like to say to <strong>'+name+'</strong>?');document.getElementById('chatInput').placeholder='Type your message to '+name+'...';document.getElementById('chatInput').focus();},600);}
function handleComposedMessage(msg){isComposingMessage=false;document.getElementById('chatInput').placeholder='Ask Artur anything…';setTimeout(()=>{const cm=document.getElementById('chatMessages');const d=document.createElement('div');d.className='chat-message bot';d.innerHTML='<div><div class="message-bubble">📝 Message to <strong>'+composingMessageTo+'</strong>:<br><br><em>"'+msg+'"</em><br><br>Ready to send?</div><div style="display: flex; gap: 8px; margin-top: 12px;"><button class="btn" onclick="editMessage(this)">Edit</button><button class="btn btn-success" onclick="sendFinalMessage(this,\''+encodeURIComponent(msg)+'\')">Send</button></div></div>';cm.appendChild(d);cm.scrollTop=cm.scrollHeight;},600);}
function editMessage(btn){btn.parentElement.style.display='none';addChatMessage('Edit',true);isComposingMessage=true;setTimeout(()=>{addChatMessage('✍️ Type your new message below.');document.getElementById('chatInput').placeholder='Type your message to '+composingMessageTo+'...';document.getElementById('chatInput').focus();},600);}
function sendFinalMessage(btn,encodedMsg){btn.parentElement.style.display='none';const msg=decodeURIComponent(encodedMsg);addChatMessage('Send',true);setTimeout(()=>{addChatMessage('✅ Done! Your message has been sent to <strong>'+composingMessageTo+'</strong>!');addSentMessageToData(composingMessageTo,msg);composingMessageTo='';},600);}
function sendContactMessage(){const msg=document.getElementById('messageText').value.trim();const name=document.getElementById('messageModalName').textContent;closeModal('messageModal');if(isDesktopView()){addChatMessage('Send message to '+name,true);setTimeout(()=>addChatMessage('✉️ Your message has been <strong>sent</strong>!'),600);}else{document.getElementById('successTitle').textContent='Message Sent!';document.getElementById('successMessage').textContent='Your message has been delivered.';document.getElementById('successModal').classList.add('show');}if(msg)addSentMessageToData(name,msg);}
function addSentMessageToData(to,msg){const now=new Date();const ts=now.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',hour12:true});messagesData.sent.unshift({id:Date.now(),to,subject:'Message to '+to,message:msg,time:ts});updateMessageFilterCount();}
function showComposeModal(){document.getElementById('composeTo').value='';document.getElementById('composeSubject').value='';document.getElementById('composeMessage').value='';document.getElementById('composeModal').classList.add('show');}
function sendNewMessage(){const to=document.getElementById('composeTo').value.trim();const subj=document.getElementById('composeSubject').value.trim();const msg=document.getElementById('composeMessage').value.trim();if(!to||!msg){alert('Please fill in recipient and message.');return;}const ts=new Date().toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',hour12:true});messagesData.sent.unshift({id:Date.now(),to,subject:subj||'(No subject)',message:msg,time:ts});closeModal('composeModal');updateMessageFilterCount();if(isDesktopView())addChatMessage('📤 Your message to <strong>'+to+'</strong> has been sent!');else{document.getElementById('successTitle').textContent='Message Sent!';document.getElementById('successMessage').textContent='Your message has been delivered.';document.getElementById('successModal').classList.add('show');}}
function selectMessageFilter(filter,text,e){e.stopPropagation();document.querySelectorAll('#messageFilterMenu .menu-item').forEach(i=>i.classList.remove('active'));e.target.closest('.menu-item').classList.add('active');document.getElementById('messageFilterMenu').classList.remove('show');document.getElementById('messageFilterText').textContent=text;currentMessageFilter=filter;renderInboxMessages();updateMessageFilterCount();}
function updateMessageFilterCount(){const all=messagesData.inbox.length;const unread=messagesData.inbox.filter(m=>m.unread).length;const read=all-unread;const sent=messagesData.sent.length;let count=all;if(currentMessageFilter==='unread')count=unread;else if(currentMessageFilter==='read')count=read;else if(currentMessageFilter==='sent')count=sent;document.getElementById('messageFilterCount').textContent=count;const sentEl=document.getElementById('sentFilterCount');if(sentEl)sentEl.textContent=sent;}
function searchMessages(){const q=document.getElementById('messageSearchInput').value.toLowerCase().trim();const sel=selectedPropertiesMessages;if(currentMessageFilter==='sent'){document.getElementById('inboxList').innerHTML=messagesData.sent.filter(m=>{if(!q)return true;return m.to.toLowerCase().includes(q)||m.subject.toLowerCase().includes(q)||(m.message&&m.message.toLowerCase().includes(q));}).map(m=>'<div class="visit-card"><div class="visit-card-content"><div class="visit-info"><h3>'+m.subject+'</h3><p class="msg-preview">'+(m.message?m.message.substring(0,80)+(m.message.length>80?'...':''):'')+'</p><div class="visit-meta-row"><span><strong>'+m.time+'</strong></span><span>to <strong>'+m.to+'</strong></span></div></div></div></div>').join('')||'<p class="empty-state">No messages found.</p>';return;}document.getElementById('inboxList').innerHTML=messagesData.inbox.filter(m=>{if(!sel.includes('all')&&!sel.some(p=>m.subject.includes(p)))return false;if(currentMessageFilter==='unread'&&!m.unread)return false;if(currentMessageFilter==='read'&&m.unread)return false;if(!q)return true;return m.sender.toLowerCase().includes(q)||m.subject.toLowerCase().includes(q)||m.thread.some(t=>t.text.toLowerCase().includes(q));}).sort((a,b)=>(b.unread?1:0)-(a.unread?1:0)).map(m=>{const preview=m.thread.length>0?m.thread[m.thread.length-1].text.substring(0,80)+(m.thread[m.thread.length-1].text.length>80?'...':''):'';return '<div class="visit-card '+(m.unread?'unread':'')+'" data-id="'+m.id+'" onclick="selectInboxMessage('+m.id+')"><div class="visit-card-content"><div class="visit-info"><h3>'+m.subject+(m.unread?' <span class="status-badge new">Unread</span>':'')+'</h3><p class="msg-preview">'+preview+'</p><div class="visit-meta-row"><span><strong>'+m.time+'</strong></span><span>from <strong>'+m.sender+'</strong></span><button class="contact-icon-btn" onclick="event.stopPropagation(); showMessageModal(\''+m.sender+'\', \''+m.subject+'\', \''+m.email+'\', \''+m.phone+'\', \'Reply to\')"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg></button></div></div><div class="visit-actions"><button class="btn" onclick="event.stopPropagation(); selectInboxMessage('+m.id+')">View Message</button></div></div></div>';}).join('')||'<p class="empty-state">No messages found.</p>';}
function selectInboxMessage(id){selectedMessageId=id;const m=messagesData.inbox.find(x=>x.id===id);if(!m)return;if(m.unread){m.unread=false;m.status='read';updateMessagesBadge();}renderInboxMessages();if(!isDesktopView()){openMobileMessageView(m);return;}const cm=document.getElementById('chatMessages');let ch='<div class="chat-message bot"><div><div class="message-bubble">📬 <strong>'+m.subject+'</strong><div style="margin-top: 8px; font-size: 13px; color: var(--c-text-secondary);"><div>'+m.sender+'</div>'+(m.phone?'<div>'+m.phone+'</div>':'')+(m.email?'<div>'+m.email+'</div>':'')+'</div></div></div></div>';m.thread.forEach(t=>{const docs=renderDocumentsHtml(t.documents);if(t.type==='incoming')ch+='<div class="chat-message bot"><div><div class="message-bubble" style="background: var(--c-bg-light); border-radius: 14px;"><strong>'+t.sender+'</strong><br>'+t.text+docs+'</div></div></div>';else ch+='<div class="chat-message user"><div><div class="message-bubble">'+t.text+docs+'</div></div></div>';});ch+='<div class="chat-message bot"><div><div class="message-bubble">Would you like to respond?</div><div style="display: flex; gap: 8px; margin-top: 12px;"><button class="btn btn-p" onclick="startReplyInChat('+m.id+')">Reply</button></div></div></div>';cm.innerHTML=ch;cm.scrollTop=cm.scrollHeight;document.getElementById('chatInput').placeholder='Reply to '+m.sender+'...';isReplyingToMessage=true;replyingToMessageId=id;}
function startReplyInChat(id){const m=messagesData.inbox.find(x=>x.id===id);if(!m)return;isReplyingToMessage=true;replyingToMessageId=id;document.getElementById('chatInput').placeholder='Type your reply to '+m.sender+'...';document.getElementById('chatInput').focus();addChatMessage('✍️ Type your reply below and press Enter.');}
function renderInboxMessages(){const sel=selectedPropertiesMessages;if(currentMessageFilter==='sent'){document.getElementById('inboxList').innerHTML=messagesData.sent.length>0?messagesData.sent.map(m=>'<div class="visit-card"><div class="visit-card-content"><div class="visit-info"><h3>'+m.subject+'</h3><p class="msg-preview">'+(m.message?m.message.substring(0,80)+(m.message.length>80?'...':''):'')+'</p><div class="visit-meta-row"><span><strong>'+m.time+'</strong></span><span>to <strong>'+m.to+'</strong></span></div></div></div></div>').join(''):'<p class="empty-state">No messages have been sent yet.</p>';return;}document.getElementById('inboxList').innerHTML=messagesData.inbox.filter(m=>{if(sel.includes('all'))return true;return sel.some(p=>m.subject.includes(p));}).filter(m=>{if(currentMessageFilter==='all')return true;if(currentMessageFilter==='unread')return m.unread;if(currentMessageFilter==='read')return !m.unread;return true;}).sort((a,b)=>(b.unread?1:0)-(a.unread?1:0)).map(m=>{const preview=m.thread.length>0?m.thread[m.thread.length-1].text.substring(0,80)+(m.thread[m.thread.length-1].text.length>80?'...':''):'';return '<div class="visit-card '+(m.unread?'unread':'')+'" data-id="'+m.id+'" onclick="selectInboxMessage('+m.id+')"><div class="visit-card-content"><div class="visit-info"><h3>'+m.subject+(m.unread?' <span class="status-badge new">Unread</span>':'')+'</h3><p class="msg-preview">'+preview+'</p><div class="visit-meta-row"><span><strong>'+m.time+'</strong></span><span>from <strong>'+m.sender+'</strong></span><button class="contact-icon-btn" onclick="event.stopPropagation(); showMessageModal(\''+m.sender+'\', \''+m.subject+'\', \''+m.email+'\', \''+m.phone+'\', \'Reply to\')"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg></button></div></div><div class="visit-actions"><button class="btn" onclick="event.stopPropagation(); selectInboxMessage('+m.id+')">View Message</button></div></div></div>';}).join('')||'<p class="empty-state">No messages found.</p>';}
function updateMessagesBadge(){const unread=messagesData.inbox.filter(m=>m.unread).length;const b=document.getElementById('messagesBadge');if(unread>0){b.textContent=unread;b.style.display='flex';}else b.style.display='none';updateMobileBadges();}

// ===== MOBILE MESSAGES =====
function openMobileMessageView(m){currentMobileMessageId=m.id;document.getElementById('mobileMessageSubject').textContent=m.subject;document.getElementById('mobileMessageStatus').innerHTML='<strong>'+m.sender+'</strong>'+(m.phone?' · <a href="tel:'+m.phone+'" style="color: var(--c-text-secondary); text-decoration: none;">'+m.phone+'</a>':'')+(m.email?' · <a href="mailto:'+m.email+'" style="color: var(--c-text-secondary); text-decoration: none;">'+m.email+'</a>':'');let th='';m.thread.forEach(t=>{const docs=renderDocumentsHtml(t.documents);if(t.type==='incoming')th+='<div class="mobile-thread-message incoming"><div class="mobile-thread-bubble"><div class="mobile-thread-text">'+t.text+'</div>'+docs+'<div class="mobile-thread-time">'+t.time+'</div></div></div>';else th+='<div class="mobile-thread-message outgoing"><div class="mobile-thread-bubble"><div class="mobile-thread-text">'+t.text+'</div>'+docs+'<div class="mobile-thread-time">'+t.time+'</div></div></div>';});document.getElementById('mobileMessageThread').innerHTML=th;document.getElementById('mobileMessageView').classList.add('show');document.getElementById('mobileReplyInput').placeholder='Reply to '+m.sender+'...';}
function closeMobileMessageView(){document.getElementById('mobileMessageView').classList.remove('show');currentMobileMessageId=null;}
function handleMobileReplyKeypress(e){if(e.key==='Enter')sendMobileReply();}
function sendMobileReply(){const i=document.getElementById('mobileReplyInput');const t=i.value.trim();if(!t&&mobilePendingFiles.length===0)return;if(!currentMobileMessageId)return;const m=messagesData.inbox.find(x=>x.id===currentMobileMessageId);if(!m)return;m.thread.push({type:'outgoing',text:t||'Sent attachment(s)',sender:'You',time:'Just now',documents:[...mobilePendingFiles]});m.status='replied';i.value='';mobilePendingFiles=[];renderMobilePendingAttachments();openMobileMessageView(m);document.getElementById('mobileMessageThread').scrollTop=document.getElementById('mobileMessageThread').scrollHeight;renderInboxMessages();showMobileToast('Reply sent!');}
function triggerMobileFileUpload(){document.getElementById('mobileFileInput').click();}
function handleMobileFileSelect(e){const f=e.target.files;for(let i=0;i<f.length;i++)mobilePendingFiles.push({name:f[i].name,size:formatFileSize(f[i].size),type:f[i].name.split('.').pop().toLowerCase()});renderMobilePendingAttachments();e.target.value='';}
function renderMobilePendingAttachments(){const c=document.getElementById('mobilePendingAttachments');if(mobilePendingFiles.length===0){c.style.display='none';return;}c.style.display='flex';c.innerHTML=mobilePendingFiles.map((f,i)=>'<div class="pending-attachment">'+f.name+'<button onclick="removeMobilePendingFile('+i+')">×</button></div>').join('');}
function removeMobilePendingFile(i){mobilePendingFiles.splice(i,1);renderMobilePendingAttachments();}
function renderDocumentsHtml(docs){if(!docs||docs.length===0)return'';let h='<div class="message-documents">';docs.forEach(d=>{const it=d.type==='pdf'?'pdf':(d.type==='doc'||d.type==='docx'?'doc':'img');const ix=d.type==='pdf'?'PDF':(d.type==='doc'||d.type==='docx'?'DOC':'IMG');h+='<div class="document-attachment" onclick="viewDocument(\''+encodeURIComponent(d.name)+'\')"><div class="document-icon '+it+'">'+ix+'</div><div class="document-info"><div class="document-name">'+d.name+'</div><div class="document-size">'+d.size+'</div></div></div>';});return h+'</div>';}
function viewDocument(en){const n=decodeURIComponent(en);document.getElementById('documentViewerTitle').textContent=n;document.getElementById('documentViewerModal').classList.add('show');}
function downloadDocument(){showMobileToast('📥 Downloading...');}

// ===== FILTERS =====
function selectOfferFilter(s,t,c,e){e.stopPropagation();document.querySelectorAll('#offerFilterMenu .menu-item').forEach(i=>i.classList.remove('active'));e.target.closest('.menu-item').classList.add('active');document.getElementById('offerFilterMenu').classList.remove('show');const rc=document.querySelectorAll('#offersReceived .visit-card'),sc=document.querySelectorAll('#offersSent .visit-card');let vc=0;if(s==='all'){document.getElementById('offersReceived').style.display='block';document.getElementById('offersSent').style.display='block';rc.forEach(c=>{c.style.display='block';vc++;});sc.forEach(c=>{c.style.display='block';vc++;});}else if(s==='received'){document.getElementById('offersReceived').style.display='block';document.getElementById('offersSent').style.display='none';rc.forEach(c=>{c.style.display='block';vc++;});}else if(s==='sent'){document.getElementById('offersReceived').style.display='none';document.getElementById('offersSent').style.display='block';sc.forEach(c=>{c.style.display='block';vc++;});}document.getElementById('offerFilterText').textContent=t;document.getElementById('offerFilterCount').textContent=vc;}
function selectFilter(s,t,c,e){e.stopPropagation();document.querySelectorAll('#filterDropdownMenu .menu-item').forEach(i=>i.classList.remove('active'));e.target.closest('.menu-item').classList.add('active');document.getElementById('filterDropdownMenu').classList.remove('show');const rc=document.querySelectorAll('#visitsReceived .visit-card'),rq=document.querySelectorAll('#visitsRequested .visit-card');let vc=0;if(s==='all'){document.getElementById('visitsReceived').style.display='block';document.getElementById('visitsRequested').style.display='block';rc.forEach(c=>{c.style.display='block';vc++;});rq.forEach(c=>{c.style.display='block';vc++;});}else if(s==='received'){document.getElementById('visitsReceived').style.display='block';document.getElementById('visitsRequested').style.display='none';rc.forEach(c=>{c.style.display='block';vc++;});}else if(s==='requested'){document.getElementById('visitsReceived').style.display='none';document.getElementById('visitsRequested').style.display='block';rq.forEach(c=>{c.style.display='block';vc++;});}document.getElementById('filterDropdownText').textContent=t;document.getElementById('filterDropdownCount').textContent=vc;}

// ===== VISITS =====
function showDeclineVisitModal(btn,buyerName,propertyAddress){currentVisitCard=btn.closest('.visit-card');currentBuyerName=buyerName;currentPropertyAddress=propertyAddress;if(isDesktopView()){addChatMessage('Decline visit',true);setTimeout(()=>{const cm=document.getElementById('chatMessages');const d=document.createElement('div');d.className='chat-message bot';d.innerHTML='<div><div class="message-bubble">Just checking 😄 This will decline the visit and notify the buyer.</div><div style="display: flex; gap: 8px; margin-top: 12px;"><button class="btn" onclick="cancelDeclineChat(this)">Keep it</button><button class="btn btn-accent" onclick="rescheduleVisitChat(this)">Reschedule</button><button class="btn btn-danger" onclick="confirmDeclineVisitChat(this)">Decline it</button></div></div>';cm.appendChild(d);cm.scrollTop=cm.scrollHeight;},600);}else document.getElementById('declineVisitModal').classList.add('show');}
function cancelDeclineChat(btn){btn.parentElement.style.display='none';addChatMessage('Cancel',true);setTimeout(()=>addChatMessage('No problem! The visit request is still pending.'),600);}
function rescheduleVisitChat(btn){btn.parentElement.style.display='none';addChatMessage('Reschedule',true);setTimeout(()=>addChatMessage('📅 Done! Reschedule request sent.<br><br>📧 We\'ll automatically send a reschedule request to the lead and an email to you to confirm it.'),600);updateVisitCardStatus(currentVisitCard,'rescheduling');updateVisitBadge();}
function confirmDeclineVisitChat(btn){btn.parentElement.style.display='none';addChatMessage('Decline it',true);setTimeout(()=>addChatMessage('Done! The visit has been declined.<br><br>📧 We\'ll automatically send a decline message to the lead. Keep pushing!'),600);updateVisitCardStatus(currentVisitCard,'declined');updateVisitBadge();}
function confirmDeclineVisit(){closeModal('declineVisitModal');if(isDesktopView()){addChatMessage('Decline it',true);setTimeout(()=>addChatMessage('👍 Done! The visit has been declined.'),600);}else{document.getElementById('successTitle').textContent='Done!';document.getElementById('successMessage').innerHTML='The visit has been declined.';document.getElementById('successModal').classList.add('show');}updateVisitCardStatus(currentVisitCard,'declined');updateVisitBadge();}
function rescheduleVisit(){closeModal('declineVisitModal');if(isDesktopView()){addChatMessage('Reschedule',true);setTimeout(()=>addChatMessage('📅 Done! Reschedule request sent.'),600);}else{document.getElementById('successTitle').textContent='Reschedule Request Sent';document.getElementById('successMessage').innerHTML='📧 We\'ll send a reschedule request to the lead.';document.getElementById('successModal').classList.add('show');}updateVisitCardStatus(currentVisitCard,'rescheduling');updateVisitBadge();}
function acceptVisit(btn,buyerName,propertyAddress){const card=btn.closest('.visit-card');if(isDesktopView()){addChatMessage('Accept visit',true);setTimeout(()=>addChatMessage('📅 Well done! We\'ll send a confirmation to the lead and an email to you.'),600);}else{document.getElementById('successIcon').textContent='👍';document.getElementById('successTitle').textContent='Well done!';document.getElementById('successMessage').innerHTML='📅 We\'ll send a confirmation to the lead.';document.getElementById('successModal').classList.add('show');}updateVisitCardStatus(card,'accepted');updateVisitBadge();}
function showCancelVisitModal(ownerName,propertyAddress,cardId){currentCancelOwnerName=ownerName;currentCancelPropertyAddress=propertyAddress;currentCancelCardId=cardId;const card=document.getElementById(cardId);let dt='';if(card){const mr=card.querySelector('.visit-meta-row strong');if(mr)dt=mr.textContent;}if(isDesktopView()){addChatMessage('Cancel visit',true);setTimeout(()=>{const cm=document.getElementById('chatMessages');const d=document.createElement('div');d.className='chat-message bot';d.innerHTML='<div><div class="message-bubble">Hold on 👀 This will cancel the visit at <strong>'+propertyAddress+'</strong>'+(dt?' on <strong>'+dt+'</strong>':'')+' and we\'ll notify <strong>'+ownerName+'</strong>.</div><div style="display: flex; gap: 8px; margin-top: 12px;"><button class="btn" onclick="keepVisitChat(this)">Keep it</button><button class="btn btn-accent" onclick="rescheduleRequestedVisitChat(this)">Reschedule</button><button class="btn btn-danger" onclick="confirmCancelVisitChat(this)">Cancel it</button></div></div>';cm.appendChild(d);cm.scrollTop=cm.scrollHeight;},600);}else{document.getElementById('cancelVisitModalText').innerHTML='This will cancel the visit at <strong>'+propertyAddress+'</strong> and we\'ll notify <strong>'+ownerName+'</strong>.';document.getElementById('cancelVisitModal').classList.add('show');}}
function keepVisitChat(btn){btn.parentElement.style.display='none';addChatMessage('Keep Visit',true);setTimeout(()=>addChatMessage('No problem! Your visit is still scheduled.'),600);}
function rescheduleRequestedVisitChat(btn){btn.parentElement.style.display='none';addChatMessage('Reschedule',true);setTimeout(()=>addChatMessage('📅 Done! Reschedule request sent.'),600);}
function confirmCancelVisitChat(btn){btn.parentElement.style.display='none';addChatMessage('Cancel Visit',true);setTimeout(()=>addChatMessage('😔 We\'ll send your cancellation request to the seller.'),600);updateRequestedVisitStatus(currentCancelCardId,'cancelled');}
function rescheduleRequestedVisit(){closeModal('cancelVisitModal');document.getElementById('successIcon').textContent='👍';document.getElementById('successTitle').textContent='Reschedule Request Sent';document.getElementById('successMessage').innerHTML='📧 We\'ll send a reschedule request.';document.getElementById('successModal').classList.add('show');}
function confirmCancelVisit(){closeModal('cancelVisitModal');document.getElementById('successIcon').textContent='😔';document.getElementById('successTitle').textContent='Visit Cancelled';document.getElementById('successMessage').innerHTML='We\'ll send your cancellation to the seller.';document.getElementById('successModal').classList.add('show');updateRequestedVisitStatus(currentCancelCardId,'cancelled');}
function updateRequestedVisitStatus(cardId,status){if(!cardId)return;const card=document.getElementById(cardId);if(!card)return;const badge=card.querySelector('.visit-meta-row .status-badge');const ad=card.querySelector('.visit-actions');if(status==='cancelled'){if(badge){badge.className='status-badge';badge.style.background='var(--c-error-bg)';badge.style.color='var(--c-error)';badge.textContent='Cancelled';}if(ad)ad.innerHTML='';}}
function updateVisitCardStatus(card,status){if(!card)return;const badge=card.querySelector('.visit-meta-row .status-badge');const ad=card.querySelector('.visit-actions');if(status==='declined'){if(badge){badge.className='status-badge';badge.style.background='var(--c-error-bg)';badge.style.color='var(--c-error)';badge.textContent='Declined';}if(ad)ad.innerHTML='';}else if(status==='accepted'){if(badge){badge.className='status-badge accepted';badge.textContent='Accepted';}const cid=card.id||'visit-'+Date.now();card.id=cid;const bn=card.querySelector('.visit-meta-row strong:last-of-type')?.textContent||'the buyer';const pn=card.querySelector('.address-main')?.textContent||'the property';if(ad)ad.innerHTML='<button class="btn" onclick="showCancelVisitModal(\''+bn+'\', \''+pn+'\', \''+cid+'\')">Cancel</button>';}else if(status==='rescheduling'){if(badge){badge.className='status-badge';badge.style.background='#fef9ed';badge.style.color='var(--c-warning)';badge.textContent='Rescheduling';}if(ad)ad.innerHTML='';}}
function updateVisitBadge(){pendingVisitsCount--;const b=document.getElementById('visitsBadge');if(pendingVisitsCount>0)b.textContent=pendingVisitsCount;else b.style.display='none';updateMobileBadges();}

// ===== OFFERS =====
function viewOffer(btn){const card=btn.closest('.visit-card');const title=card.querySelector('h3').childNodes[0].textContent.trim();if(isDesktopView()){addChatMessage('📄 <strong>Viewing offer for '+title+'</strong><br><br>I can help you review, compare, counter, or accept. What would you like?');}else{openMobileChat();}}

// ===== ACCOUNT =====
function switchAccountTab(tab){document.getElementById('profileTab').classList.toggle('active',tab==='profile');document.getElementById('invoicesTab').classList.toggle('active',tab==='invoices');document.getElementById('notificationsTab').classList.toggle('active',tab==='notifications');document.getElementById('accountProfile').style.display=tab==='profile'?'block':'none';document.getElementById('accountInvoices').style.display=tab==='invoices'?'block':'none';document.getElementById('accountNotifications').style.display=tab==='notifications'?'block':'none';}
function saveProfile(){const primary=document.getElementById('primaryPhone');const secondary=document.getElementById('secondaryPhone');const primaryValid=validatePhone(primary);const secondaryValid=secondary.value.length===0||validatePhone(secondary);if(!primaryValid||!secondaryValid)return;document.getElementById('successTitle').textContent='Profile Saved';document.getElementById('successMessage').textContent='Your changes have been saved successfully.';document.getElementById('successModal').classList.add('show');document.getElementById('phoneUpdateOption').style.display='none';}
function saveNotifications(){document.getElementById('successTitle').textContent='Preferences Saved';document.getElementById('successMessage').textContent='Your notification preferences have been updated.';document.getElementById('successModal').classList.add('show');}
function toggleInfoBubble(el){event.stopPropagation();document.querySelectorAll('.info-bubble').forEach(b=>{if(b!==el)b.classList.remove('active');});el.classList.toggle('active');}
function showPhoneUpdateOption(){const original='(305) 555-1234';const current=document.getElementById('primaryPhone').value;document.getElementById('phoneUpdateOption').style.display=current!==original?'block':'none';}
function formatPhoneNumber(input){let val=input.value.replace(/\D/g,'');if(val.length>10)val=val.substring(0,10);let formatted='';if(val.length>0)formatted='('+val.substring(0,3);if(val.length>=3)formatted+=') ';if(val.length>3)formatted+=val.substring(3,6);if(val.length>=6)formatted+='-'+val.substring(6,10);input.value=formatted;validatePhone(input);}
function validatePhone(input){const errId=input.id+'Error';const errEl=document.getElementById(errId);if(!errEl)return true;const val=input.value.replace(/\D/g,'');errEl.textContent='';input.style.borderColor='';if(val.length===0)return true;if(val.length<10){errEl.textContent='Phone number must be 10 digits';input.style.borderColor='var(--c-error)';return false;}if(/^(\d)\1{9}$/.test(val)){errEl.textContent='Invalid phone number';input.style.borderColor='var(--c-error)';return false;}const areaCode=val.substring(0,3);if(areaCode==='000'||areaCode==='111'||areaCode==='555'){errEl.textContent='Invalid area code';input.style.borderColor='var(--c-error)';return false;}input.style.borderColor='var(--c-success)';return true;}
function downloadInvoice(id){showMobileToast('🖨️ Printing '+id+'...');}
function downloadContract(id){showMobileToast('📥 Downloading document...');}

// ===== CONTRACTS =====
function selectState(state,e){e.stopPropagation();document.querySelectorAll('#stateFilterMenu .menu-item').forEach(i=>i.classList.remove('active'));e.target.classList.add('active');document.getElementById('stateFilterText').textContent=state;document.getElementById('stateFilterMenu').classList.remove('show');}
function switchContractTab(tab){document.getElementById('sellTab').classList.toggle('active',tab==='sell');document.getElementById('rentTab').classList.toggle('active',tab==='rent');document.getElementById('disclosureTab').classList.toggle('active',tab==='disclosure');document.getElementById('agreementTab').classList.toggle('active',tab==='agreement');document.getElementById('contractsSell').style.display=tab==='sell'?'flex':'none';document.getElementById('contractsRent').style.display=tab==='rent'?'flex':'none';document.getElementById('contractsDisclosure').style.display=tab==='disclosure'?'flex':'none';document.getElementById('contractsAgreement').style.display=tab==='agreement'?'flex':'none';}

// ===== PROPERTIES =====
function addNewProperty(){document.getElementById('submitPropertyPage').style.display='block';document.body.style.overflow='hidden';}
function closeSubmitProperty(e){e.preventDefault();document.getElementById('submitPropertyPage').style.display='none';document.body.style.overflow='';}
function handleListProperty(){const addr=document.getElementById('submitPropertyAddress').value.trim();if(!addr){showMobileToast('Please enter a property address');return;}showMobileToast('🏠 Starting listing for: '+addr);}
function deleteProperty(id,name){const card=document.querySelector('[data-property-id="'+id+'"]');if(card){card.remove();properties=properties.filter(p=>!p.id.includes(name));initPropertyFilters();if(isDesktopView())addChatMessage('🗑️ Property <strong>'+name+'</strong> has been deleted.');}}

// ===== PROPERTY FILTERS =====
function renderPropertyFilter(){document.getElementById('propertyFilterMenu').innerHTML=properties.map(p=>'<button class="menu-item '+(selectedProperties.includes(p.id)?'active':'')+'" onclick="selectProperty(\''+p.id+'\', event)">'+(p.id==='all'?p.name:p.name.split(',')[0])+'</button>').join('');}
function selectProperty(pid,e){e.stopPropagation();if(pid==='all')selectedProperties=['all'];else{if(selectedProperties.includes('all'))selectedProperties=[pid];else if(selectedProperties.includes(pid)){selectedProperties=selectedProperties.filter(p=>p!==pid);if(selectedProperties.length===0)selectedProperties=['all'];}else selectedProperties.push(pid);}updatePropertyFilterButton();renderPropertyFilter();renderCalendar();}
function updatePropertyFilterButton(){let text='All Properties';if(!selectedProperties.includes('all')){text=selectedProperties.length===1?selectedProperties[0].split(',')[0]:selectedProperties.length+' Properties';}document.getElementById('propertyFilterText').textContent=text;}
function togglePagePropertyFilter(page,e){e.stopPropagation();e.preventDefault();const m=document.getElementById(page+'PropertyFilterMenu');const isOpen=m.classList.contains('show');closeAllDropdowns();if(!isOpen){m.classList.add('show');if(window.innerWidth<=1024)document.body.style.overflow='hidden';renderPagePropertyFilter(page);}}
function renderPagePropertyFilter(page){const sel=page==='offers'?selectedPropertiesOffers:(page==='visits'?selectedPropertiesVisits:(page==='properties'?selectedPropertiesProperties:selectedPropertiesMessages));document.getElementById(page+'PropertyFilterMenu').innerHTML=properties.map(p=>'<button class="menu-item '+(sel.includes(p.id)?'active':'')+'" onclick="selectPageProperty(\''+page+'\',\''+p.id+'\',event)">'+(p.id==='all'?p.name:p.name.split(',')[0])+'</button>').join('');}
function selectPageProperty(page,pid,e){e.stopPropagation();let sel=page==='offers'?selectedPropertiesOffers:(page==='visits'?selectedPropertiesVisits:(page==='properties'?selectedPropertiesProperties:selectedPropertiesMessages));if(pid==='all')sel=['all'];else{if(sel.includes('all'))sel=[pid];else if(sel.includes(pid)){sel=sel.filter(p=>p!==pid);if(sel.length===0)sel=['all'];}else sel.push(pid);}if(page==='offers')selectedPropertiesOffers=sel;else if(page==='visits')selectedPropertiesVisits=sel;else if(page==='properties')selectedPropertiesProperties=sel;else selectedPropertiesMessages=sel;updatePagePropertyFilterButton(page);renderPagePropertyFilter(page);applyPagePropertyFilter(page);}
function updatePagePropertyFilterButton(page){const sel=page==='offers'?selectedPropertiesOffers:(page==='visits'?selectedPropertiesVisits:(page==='properties'?selectedPropertiesProperties:selectedPropertiesMessages));let text='All Properties';if(!sel.includes('all')){text=sel.length===1?sel[0].split(',')[0]:sel.length+' Properties';}document.getElementById(page+'PropertyFilterText').textContent=text;}
function applyPagePropertyFilter(page){if(page==='offers'){const sel=selectedPropertiesOffers;document.querySelectorAll('#offersReceived .visit-card, #offersSent .visit-card').forEach(card=>{const title=card.querySelector('h3')?.textContent||'';const show=sel.includes('all')||sel.some(p=>title.includes(p));card.style.display=show?'block':'none';});}else if(page==='visits'){const sel=selectedPropertiesVisits;document.querySelectorAll('#visitsReceived .visit-card, #visitsRequested .visit-card').forEach(card=>{const title=card.querySelector('h3')?.textContent||'';const show=sel.includes('all')||sel.some(p=>title.includes(p));card.style.display=show?'block':'none';});}else if(page==='properties'){const sel=selectedPropertiesProperties;document.querySelectorAll('#propertyGrid .property-card').forEach(card=>{const title=card.querySelector('h3')?.textContent||'';const show=sel.includes('all')||sel.some(p=>title.includes(p));card.style.display=show?'block':'none';});const addCard=document.querySelector('#propertyGrid .add-property-card');if(addCard)addCard.style.display='block';}else if(page==='messages'){renderInboxMessages();}}
function initPropertyFilters(){const hasMultiple=properties.length>2;['offers','visits','messages','calendar','properties'].forEach(page=>{const el=document.getElementById(page+'PropertyFilter');if(el)el.style.display=hasMultiple?'block':'none';});}

// ===== CALENDAR =====
function renderCalendar(){const y=currentCalendarDate.getFullYear();const mo=currentCalendarDate.getMonth();const mn=['January','February','March','April','May','June','July','August','September','October','November','December'];document.getElementById('calendarTitle').textContent=mn[mo]+' '+y;if(currentCalendarView==='month')renderMonthView(y,mo);else renderWeekView(y,mo);}
function renderMonthView(y,mo){const g=document.getElementById('calendarGrid');const fd=new Date(y,mo,1);const sd=new Date(fd);sd.setDate(sd.getDate()-fd.getDay());const td=new Date();let h='';for(let i=0;i<42;i++){const d=new Date(sd);d.setDate(sd.getDate()+i);const om=d.getMonth()!==mo;const it=d.toDateString()===td.toDateString();const de=getEventsForDate(d);let cl='calendar-day';if(om)cl+=' other-month';if(it)cl+=' today';h+='<div class="'+cl+'"><div class="calendar-day-number">'+d.getDate()+'</div><div class="calendar-events">';de.slice(0,2).forEach(e=>{const sc=e.status==='pending'?' pending':'';h+='<div class="calendar-event '+e.type+sc+'" onclick="event.stopPropagation(); showEventPopover('+e.id+', this)">'+e.shortTitle+'</div>';});if(de.length>2)h+='<div class="calendar-more">+'+(de.length-2)+' more</div>';h+='</div></div>';if(i>=34&&d.getMonth()!==mo)break;}g.innerHTML=h;}
function renderWeekView(y,mo){const g=document.getElementById('weekGrid');const sw=new Date(currentCalendarDate);sw.setDate(sw.getDate()-sw.getDay());const td=new Date();const dn=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];let h='<div class="week-header"><div class="week-header-cell"></div>';for(let i=0;i<7;i++){const d=new Date(sw);d.setDate(sw.getDate()+i);const it=d.toDateString()===td.toDateString();h+='<div class="week-header-cell'+(it?' today':'')+'"><div class="day-name">'+dn[i]+'</div><div class="day-number">'+d.getDate()+'</div></div>';}h+='</div>';for(let hr=8;hr<=18;hr++){h+='<div class="week-time-slot">'+formatHour(hr)+'</div>';for(let day=0;day<7;day++){const d=new Date(sw);d.setDate(sw.getDate()+day);const de=getEventsForDateAndHour(d,hr);h+='<div class="week-day-col"><div class="week-hour-row">';de.forEach(e=>{const sc=e.status==='pending'?' pending':'';const et=e.date.getHours()+(e.date.getMinutes()/60);const top=(et-hr)*60;h+='<div class="week-event '+e.type+sc+'" style="top: '+top+'px; height: 50px;" onclick="showEventPopover('+e.id+', this)"><div class="week-event-time">'+formatTime(e.date)+'</div><div class="week-event-title">'+e.shortTitle+'</div></div>';});h+='</div></div>';}}g.innerHTML=h;}
function getEventsForDate(d){return calendarEvents.filter(e=>e.date.getFullYear()===d.getFullYear()&&e.date.getMonth()===d.getMonth()&&e.date.getDate()===d.getDate()&&(selectedProperties.includes('all')||selectedProperties.includes(e.property)));}
function getEventsForDateAndHour(d,hr){return calendarEvents.filter(e=>e.date.getFullYear()===d.getFullYear()&&e.date.getMonth()===d.getMonth()&&e.date.getDate()===d.getDate()&&e.date.getHours()===hr&&(selectedProperties.includes('all')||selectedProperties.includes(e.property)));}
function formatHour(h){if(h===0)return'12 AM';if(h===12)return'12 PM';return h>12?(h-12)+' PM':h+' AM';}
function formatTime(d){let h=d.getHours();const m=d.getMinutes();const ap=h>=12?'PM':'AM';h=h%12||12;return h+':'+(m<10?'0':'')+m+' '+ap;}
function formatDate(d){const mn=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return mn[d.getMonth()]+' '+d.getDate()+', '+d.getFullYear();}
function prevMonth(){if(currentCalendarView==='month')currentCalendarDate.setMonth(currentCalendarDate.getMonth()-1);else currentCalendarDate.setDate(currentCalendarDate.getDate()-7);renderCalendar();}
function nextMonth(){if(currentCalendarView==='month')currentCalendarDate.setMonth(currentCalendarDate.getMonth()+1);else currentCalendarDate.setDate(currentCalendarDate.getDate()+7);renderCalendar();}
function goToToday(){currentCalendarDate=new Date(2026,0,30);renderCalendar();}
function switchCalendarView(v){currentCalendarView=v;document.getElementById('monthViewBtn').classList.toggle('active',v==='month');document.getElementById('weekViewBtn').classList.toggle('active',v==='week');document.getElementById('monthView').classList.toggle('active',v==='month');document.getElementById('weekView').classList.toggle('active',v==='week');renderCalendar();}
function showEventPopover(eid,el){const e=calendarEvents.find(x=>x.id===eid);if(!e)return;selectedEventData=e;const sl=e.status==='confirmed'?'Confirmed':(e.status==='completed'?'Completed':(e.status==='upcoming'?'Upcoming':'Pending'));const sc=e.status==='confirmed'||e.status==='completed'?'confirmed':'pending';document.getElementById('eventPopoverBadge').textContent=sl;document.getElementById('eventPopoverBadge').className='event-popover-badge '+sc;document.getElementById('eventPopoverTitle').innerHTML=e.title;document.getElementById('eventPopoverDate').textContent=formatDate(e.date);document.getElementById('eventPopoverTime').textContent=formatTime(e.date);document.getElementById('eventPopoverPerson').innerHTML=e.person?'<strong>'+e.person+'</strong>':'<em>No contact</em>';const pop=document.getElementById('eventPopover');const rect=el.getBoundingClientRect();let left=rect.left,top=rect.bottom+8;if(left+320>window.innerWidth)left=window.innerWidth-336;if(top+280>window.innerHeight)top=rect.top-280;pop.style.left=Math.max(16,left)+'px';pop.style.top=top+'px';pop.style.display='block';}
function closeEventPopover(){document.getElementById('eventPopover').style.display='none';selectedEventData=null;}
function messageFromCalendar(){if(!selectedEventData)return;closeEventPopover();showMessageModal(selectedEventData.person,selectedEventData.title,selectedEventData.email,selectedEventData.phone,'Visit at');}
function addToExternalCalendar(){if(!selectedEventData)return;const e=selectedEventData;const title=encodeURIComponent('Visit: '+e.title);window.open('https://calendar.google.com/calendar/render?action=TEMPLATE&text='+title,'_blank');showMobileToast('📅 Opening Google Calendar...');}
function openAddEventModal(){document.getElementById('addEventType').value='visit';document.getElementById('addEventTitle').value='';document.getElementById('addEventContact').value='';document.getElementById('addEventPhone').value='';document.getElementById('addEventEmail').value='';const td=new Date();document.getElementById('addEventDate').value=td.getFullYear()+'-'+String(td.getMonth()+1).padStart(2,'0')+'-'+String(td.getDate()).padStart(2,'0');updateAddEventForm();document.getElementById('addEventModal').classList.add('show');}
function updateAddEventForm(){}
function saveNewEvent(){const type=document.getElementById('addEventType').value;const prop=document.getElementById('addEventProperty').value;const title=document.getElementById('addEventTitle').value.trim();const dateVal=document.getElementById('addEventDate').value;const timeVal=document.getElementById('addEventTime').value;const contact=document.getElementById('addEventContact').value.trim();if(!title||!dateVal||!timeVal){showMobileToast('Please fill in title, date and time');return;}const[y,m,d]=dateVal.split('-').map(Number);const[h,mi]=timeVal.split(':').map(Number);const ed=new Date(y,m-1,d,h,mi);calendarEvents.push({id:Date.now(),type:type==='other'?'milestone':type,status:'upcoming',title:title+' - '+prop,shortTitle:title,date:ed,person:contact,phone:document.getElementById('addEventPhone').value,email:document.getElementById('addEventEmail').value,property:prop});closeModal('addEventModal');renderCalendar();showMobileToast('✅ Event added to calendar');if(isDesktopView())addChatMessage('✅ I\'ve added <strong>'+title+'</strong> to your calendar for <strong>'+formatDate(ed)+'</strong>.');}

// ===== EVENT LISTENERS =====
document.addEventListener('click',function(e){if(!e.target.closest('.filter-dropdown')&&!e.target.closest('.property-filter-dropdown')&&!e.target.closest('.dashboard-dropdown')&&!e.target.closest('.notifications-dropdown')&&!e.target.closest('.nav-item')&&!e.target.closest('.mobile-more-wrapper')&&!e.target.closest('.menu')){closeAllDropdowns();}if(!e.target.closest('.info-bubble')){document.querySelectorAll('.info-bubble').forEach(b=>b.classList.remove('active'));}if(!e.target.closest('.event-popover')&&!e.target.closest('.calendar-event')&&!e.target.closest('.week-event'))closeEventPopover();});
document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.remove('show');}));

// ===== INIT ON LOAD =====
window.addEventListener('load',function(){setGreeting();renderInboxMessages();updateMessagesBadge();updateMobileBadges();updateNotificationsBadge();initPropertyFilters();setTimeout(()=>{addChatMessage('👋 Hi John! I\'m <strong>Artur</strong>, your personal real estate assistant. I\'m here to guide you through every step of selling your property.<br><br>I can help you with:<br>• Reviewing and responding to offers<br>• Managing visit requests<br>• Understanding contracts<br>• Answering any questions<br><br>Just type below or click on anything you need help with!');},800);visitedPages['offers']=false;setTimeout(()=>showPageContextMessage('offers'),2500);});